[package]
name = "aarch64os"
version = "0.1.0"
authors = ["Amit Aryeh Levy <amit@amitlevy.com>"]
edition = "2018"

[dependencies]
linked_list_allocator = "0.8.11"

[profile.release]
debug = true

[build-dependencies]
cc = "1.0.25"
